# Generated by Django 4.0.4 on 2022-05-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_votergovt_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidateudma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('party', models.CharField(max_length=30)),
                ('constituency', models.CharField(max_length=50)),
            ],
        ),
    ]
