# Generated by Django 4.0.4 on 2022-05-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_candidateudma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voterregisteredudma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('phonenumber', models.CharField(max_length=10)),
                ('pannumber', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=40)),
            ],
        ),
    ]
