# Generated by Django 4.0.4 on 2022-05-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_voterregisteredudma'),
    ]

    operations = [
        migrations.CreateModel(
            name='UIDudma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pannumber', models.CharField(max_length=10)),
                ('uniqueid', models.CharField(max_length=10)),
            ],
        ),
    ]
